### PR TITLE
Remove (from WWW.DEEZER.LINK) from downloaded file

### PR DESCRIPTION
**Pull request by juliors**

### CODE REVIEW

**Comment by jsnjack** [comment]
I see no changes in your pull request or was it feature request?

**Comment by juliors** [comment]
Is a feature request.

**Comment by jsnjack** [comment]
then the right way will be to create an issue (please do that). i will close this pull request as it not actually pull request :)

**Comment by juliors** [comment]
Ok, excuse me.

**Comment by jsnjack** [comment]
no problem at all. :) i will probably look into the issue this week

**Pull request closed without merging**
